# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_author', models.CharField(max_length=30)),
                ('a_title', models.CharField(max_length=50)),
                ('a_keyWord', models.CharField(max_length=100)),
                ('a_describe', models.CharField(max_length=500)),
                ('a_column', models.IntegerField(default=1)),
                ('a_label', models.CharField(max_length=20)),
                ('a_lastTime', models.DateField(auto_now=True)),
                ('a_createTime', models.DateField(auto_now_add=True)),
                ('a_state', models.BooleanField(default=True)),
                ('a_isDelete', models.BooleanField(default=False)),
                ('a_picture', models.ImageField(null=True, upload_to='img')),
            ],
            options={
                'db_table': 'articles',
            },
            managers=[
                ('artObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_address', models.CharField(max_length=200)),
                ('p_lastTime', models.DateField(auto_now_add=True)),
                ('p_createTime', models.DateField(auto_now_add=True)),
                ('p_isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
    ]
